default: &default
  adapter: postgresql
  username: user1
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fs-blog_dev


test:
  <<: *default
  database: fs-blog_test

production:
  <<: *default
  database: fs-blog_prod
